spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quiz
    username: postgres
    password: asylka225
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/quiz
    user: postgres
    password: asylka225
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: validate
    hibernate:
      ddl-auto: validate
    show-sql: true
    generate-ddl: false


logging:
  level:
    org.flywaydb: DEBUG
    org:
      hibernate:
        SQL: DEBUG



